# Generated by Django 2.2 on 2020-06-03 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_name', models.CharField(max_length=200, unique=True)),
                ('real_name', models.FileField(max_length=1000, upload_to='')),
                ('tz', models.CharField(max_length=10)),
                ('activity_peroid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Member')),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('datail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Detail')),
            ],
        ),
    ]
