# Generated by Django 2.2 on 2020-06-04 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200603_1941'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='datail',
            new_name='detail',
        ),
    ]
