# Generated by Django 2.2 on 2020-06-04 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200604_0424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='track_activity', to='core.Detail'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='activity_peroid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member_activity', to='core.Member'),
        ),
    ]
