# Generated by Django 2.2 on 2020-06-04 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200604_0539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='real_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='detail',
            name='tz',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
