# Generated by Django 2.2 on 2020-06-04 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200604_0828'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detail',
            old_name='id_name',
            new_name='id_number',
        ),
    ]
